### ISSUE TITLE
USER STORY S2.3: Update Booking

### ISSUE THREAD

**Issue by vikdts** [vikdts/django-app#10]
Epic: #2 

### Description

As a **Site User** I can **update a booking** so that **I can make changes to an existing reservation**

### Tasks

- [x] Add Name 
- [x] Add Email
- [x] Add Phone
- [x] Add Date
- [x] Add Number of Guests
- [x] Add Time Slot
- [x] Add Optional Note
- [x] Submit Form
