### ISSUE TITLE
USER STORY S3.1: Create Booking

### ISSUE THREAD

**Issue by vikdts** [vikdts/django-app#12]
Epic: #3 

### Description

As a **Admin** I can **create a booking** so that **I can reserve a table in advance**

### Tasks

- [x] Add User
- [x] Add Email
- [x] Add Phone
- [x] Add Date
- [x] Add Number of Guests
- [x] Add Table
- [x] Add Time Slot
- [x] Add Optional Note
- [x] Save and add another
- [x] Save and continue editing
- [x] Save
