### ISSUE TITLE
USER STORY S3.3: Update Booking

### ISSUE THREAD

**Issue by vikdts** [vikdts/django-app#14]
Epic: #3 

### Description

As a **Admin** I can **update a booking** so that **I can make changes to an existing reservation**

### Tasks

- [x] Add User
- [x] Add Email
- [x] Add Phone
- [x] Add Date
- [x] Add Number of Guests
- [x] Add Table
- [x] Add Time Slot
- [x] Add Optional Note
- [x] Save and add another
- [x] Save and continue editing
- [x] Save
- [x] Delete
