### ISSUE TITLE
USER STORY S2.1: Create Booking

### ISSUE THREAD

**Issue by vikdts** [vikdts/django-app#8]
Epic: #2 

### Description

As a **Site User** I can **create a booking** so that **I can reserve a table in advance**

### Tasks

- [x] Add Name 
- [x] Add Email
- [x] Add Phone
- [x] Add Date
- [x] Add Number of Guests
- [x] Add Time Slot
- [x] Add Optional Note
- [x] Submit Form
